# permissions for end users to edit podwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podwatcher-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podwatcher
    app.kubernetes.io/part-of: podwatcher
    app.kubernetes.io/managed-by: kustomize
  name: podwatcher-editor-role
rules:
- apiGroups:
  - sregig.redhat.com
  resources:
  - podwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sregig.redhat.com
  resources:
  - podwatchers/status
  verbs:
  - get
