---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sregig.redhat.com
  resources:
  - podwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sregig.redhat.com
  resources:
  - podwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - sregig.redhat.com
  resources:
  - podwatchers/status
  verbs:
  - get
  - patch
  - update
